# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fb6498b0aad400e6279f7a1abb31a029cdca701cb6d65e229e01bf108e80a351b608cdda6286da34c47df4a79eb50b634c2beb3628fb51681b31e01a7f782b4

test:
  secret_key_base: 935af994f2c8e00c5455c74df4f4e19029f91f27ff5964d392a9a749c8735e1c67b1542f22a50ca3e19d6961a10c46f42c3a774d20624895a64eb92accc5ccc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
